name: manually build uctags for windows via MSYS2/MINGW64

on:
  workflow_dispatch:
    inputs:
      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64

      enable-manpages:
        description: whether to generate manpages
        type: boolean
        default: false

      enable-json:
        description: whether to enable json support
        type: boolean
        default: true

      enable-yaml:
        description: whether to enable yaml support
        type: boolean
        default: true

      enable-xml:
        description: whether to enable xml support
        type: boolean
        default: true

      enable-libiconv:
        description: whether to enable libiconv support
        type: boolean
        default: true

      enable-threads:
        description: whether to enable threads support
        type: boolean
        default: true

      enable-largefile:
        description: whether to enable large file support
        type: boolean
        default: true

      regex-backend:
        description: choose a regex backend to be built with
        type: choice
        options:
          - none
          - gnu-regex
          - pcre2
        default: gnu-regex

jobs:
  build:

    runs-on: windows-2022

    steps:
      - name: build
        run: |
          unset DEP_PKG
          unset CONFIGURE_ARGS

          if [ '${{ github.event.inputs.enable-threads }}' = 'false' ] ; then
              CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-threads"
          else
              CONFIGURE_ARGS="$CONFIGURE_ARGS --enable-threads"
          fi

          if [ '${{ github.event.inputs.enable-largefile }}' = 'false' ] ; then
              CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-largefile"
          else
              CONFIGURE_ARGS="$CONFIGURE_ARGS --enable-largefile"
          fi

          if [ '${{ github.event.inputs.enable-json }}' = 'false' ] ; then
              CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-json"
          else
              CONFIGURE_ARGS="$CONFIGURE_ARGS --enable-json"
              DEP_PKG="$DEP_PKG jansson"
          fi

          if [ '${{ github.event.inputs.enable-yaml }}' = 'false' ] ; then
              CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-yaml"
          else
              CONFIGURE_ARGS="$CONFIGURE_ARGS --enable-yaml"
              DEP_PKG="$DEP_PKG libyaml"
          fi

          if [ '${{ github.event.inputs.enable-xml }}' = 'false' ] ; then
              CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-xml"
          else
              CONFIGURE_ARGS="$CONFIGURE_ARGS --enable-xml"
              DEP_PKG="$DEP_PKG libxml2"
          fi

          if [ '${{ github.event.inputs.enable-libiconv }}' = 'false' ] ; then
              CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-iconv"
          else
              CONFIGURE_ARGS="$CONFIGURE_ARGS --enable-iconv"
          fi

          case ${{ github.event.inputs.regex-backend }} in
              none)
                CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-pcre2 --without-included-regex"
                ;;
              gnu-regex)
                CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-pcre2 --with-included-regex"
                ;;
              pcre2)
                CONFIGURE_ARGS="$CONFIGURE_ARGS --enable-pcre2"
                DEP_PKG="$DEP_PKG pcre2"
                ;;
              *) echo "unexpected regex-backend: ${{ github.event.inputs.regex-backend }}"
          esac

          pacman -Syy --noconfirm
          pacman -S   --noconfirm automake autoconf make pkg-config mingw-w64-x86_64-toolchain python3 file zip git

          for item in $DEP_PKG
          do
              pacman -S --noconfirm "mingw-w64-x86_64-$item"
          done

          if [ "${{ github.event.inputs.enable-manpages }}" = true ] ; then
              pip3 install -U docutils
          fi

          if [ "${{ github.event.inputs.enable-htmldocs }}" = true ] ; then
              pip3 install -U sphinx
          fi

          git config --global core.autocrlf input
          git clone --depth=1 https://github.com/universal-ctags/ctags
          cd ctags
          ./autogen.sh
          ./configure --disable-external-sort --enable-static $CONFIGURE_ARGS --prefix=$PWD/out
          make -j2
          make install

          ls -l

          file ctags.exe
          ldd  ctags.exe

          TIMESTAMP="$(date +%Y.%m.%d.%H.%M.%S)"
          OUTPUT_DIR="uctags-${TIMESTAMP}-windows-${{ github.event.inputs.target-arch }}"

          mv out "$OUTPUT_DIR"

          if [ "${{ github.event.inputs.enable-htmldocs }}" = true ] ; then
              make -C docs html
              install -d          "$OUTPUT_DIR/share/doc/"
              mv docs/_build/html "$OUTPUT_DIR/share/doc/"
          fi

          if [ "${{ github.event.inputs.enable-manpages }}" = true ] ; then
              make -C man

              install -d "$OUTPUT_DIR/share/man/man1/"
              install -d "$OUTPUT_DIR/share/man/man5/"
              install -d "$OUTPUT_DIR/share/man/man7/"
 
              cp man/*.1 "$OUTPUT_DIR/share/man/man1/"
              cp man/*.5 "$OUTPUT_DIR/share/man/man5/"
              cp man/*.7 "$OUTPUT_DIR/share/man/man7/"
          fi

          zip -9 -r "${OUTPUT_DIR}.zip" "$OUTPUT_DIR"

          mv "${OUTPUT_DIR}.zip" ${{ github.workspace }}
        shell: C:\msys64\msys2_shell.cmd -no-start -defterm -mingw64 -here -full-path -shell bash -e -x {0}


      - uses: actions/upload-artifact@v3
        with:
          name: uctags---windows-${{ github.event.inputs.target-arch }}.zip
          path: uctags-*-windows-${{ github.event.inputs.target-arch }}.zip
